[build]
  command = "npm install --prefix netlify/functions && cd web && npm run build"
  publish = "web/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
